<?php

namespace Ccis\CcisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PiecesJointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiecesJointRepository extends EntityRepository
{
}
